coinbase_adapter:
    subscribe: /api/coinbase/wsFeed/subscribe
    auth: /api/auth
    subscriptions: /api/subscriptions
    host: localhost
    port: 8080
    subscribe_body:
        type: Subscribe
        productIds: []
        channels:
            - ticker

rethinkdb:
    host: localhost
    port: 28015
    db_name: cryptobot

graphql:
    host: localhost
    port: 8080
    endpoints:
        base: /graphql

coinbase_subscriber:
    host: localhost
    port: 8080
    endpoints:
        subscribe: /subscribe
