version: "3"

services:
  realtime-db:
    image: "rethinkdb:2.4.0"
    container_name: rethinkdb
    restart: always
    ports:
    - 8000:8080
    - 28015:28015
  db-initializer:
    build: ./db-initializer
    depends_on:
      - realtime-db
    environment:
      RETHINK_HOST: ${RETHINK_DB_HOST}
    container_name: db-initializer
  graphql:
    build: ./graphql
    depends_on:
      - realtime-db
    environment:
      RETHINK_HOST: ${RETHINK_DB_HOST}
    container_name: graphql
    restart: always
    ports:
    - 9090:9090
  coinbase-subscriber:
    build: ./coinbase-subscriber
    depends_on:
      - realtime-db
    environment:
      RETHINK_HOST: ${RETHINK_DB_HOST}
    container_name: coinbase_subscriber
    restart: always
    ports:
    - 9999:9999
  coinbase-adapter:
    build: ./coinbase-adapter
    depends_on:
      - realtime-db
    environment:
      RETHINK_HOST: ${RETHINK_DB_HOST}
      CB_SANDBOX_API_KEY: ${CB_SANDBOX_API_KEY}
      CB_SANDBOX_API_SECRET: ${CB_SANDBOX_API_SECRET}
      CB_SANDBOX_API_PASSPHRASE: ${CB_SANDBOX_API_PASSPHRASE}
      COINBASE_ADAPTER_BASIC_AUTH_USER: ${COINBASE_ADAPTER_BASIC_AUTH_USER}
      COINBASE_ADAPTER_BASIC_AUTH_PWD: ${COINBASE_ADAPTER_BASIC_AUTH_PWD}
    container_name: coinbase_adapter
    restart: always
    ports:
    - 9000:9000
#  crypto-analyzer:
#    build: ./crypto-analyzer
#    depends_on:
#      - realtime-db
#      - coinbase-adapter-service
#    container_name: crypto_analyzer
#    restart: always
#    environment:
#      RETHINK_DB_HOST: ${RETHINK_DB_HOST}
#      COINBASE_ADAPTER_BASIC_AUTH_USER: ${COINBASE_ADAPTER_BASIC_AUTH_USER}
#      COINBASE_ADAPTER_BASIC_AUTH_PWD: ${COINBASE_ADAPTER_BASIC_AUTH_PWD}
#      CB_HOST: ${CB_HOST}