version: "3"

services:
  rethinkdb:
    image: rethinkdb:2.4.0
    container_name: rethinkdb
    hostname: rethinkdb
    ports:
      - "${RETHINKDB_PORT}:8080"
      - "28015:28015"
    restart: always
  db-initializer:
    build: ./db-initializer
    depends_on:
      - rethinkdb
    environment:
      RETHINK_HOST: rethinkdb
    container_name: db-initializer
  graphql:
    image: ghcr.io/pagidas/graphql
    container_name: graphql
    hostname: graphql
    ports:
      - "${GRAPHQL_PORT}:8080"
    environment:
      RETHINK_HOST: rethinkdb
    depends_on:
      - rethinkdb
    restart: always
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 5s
  coinbase-subscriber:
    image: ghcr.io/pagidas/coinbase-subscriber
    container_name: coinbase-subscriber
    hostname: coinbase-subscriber
    ports:
      - "${CB_SUBSCRIBER_PORT}:8080"
    environment:
      RETHINKDB_HOST: rethinkdb
    depends_on:
      - rethinkdb
    restart: always
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 5s
  coinbase-adapter:
    image: ghcr.io/pagidas/coinbase-adapter
    container_name: coinbase-adapter
    hostname: coinbase-adapter
    ports:
      - "${CB_ADAPTER_PORT}:8080"
    environment:
      CB_SANDBOX_API_KEY: ${CB_SANDBOX_API_KEY}
      CB_SANDBOX_API_SECRET: ${CB_SANDBOX_API_SECRET}
      CB_SANDBOX_API_PASSPHRASE: ${CB_SANDBOX_API_PASSPHRASE}
    restart: always
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 5s
  crypto-analyzer:
    image: ghcr.io/pagidas/crypto-analyzer
    container_name: crypto-analyzer
    hostname: crypto-analyzer
    environment:
      RETHINK_DB_HOST: rethinkdb
      CB_HOST: coinbase-adapter
      CB_SUBSCRIBER_HOST: coinbase-subscriber
      GQL_HOST: graphql
      COINBASE_ADAPTER_BASIC_AUTH_USER: ${COINBASE_ADAPTER_BASIC_AUTH_USER}
      COINBASE_ADAPTER_BASIC_AUTH_PWD: ${COINBASE_ADAPTER_BASIC_AUTH_PWD}
    depends_on:
      - rethinkdb
      - coinbase-adapter
    restart: always