micronaut:
  server:
    port: 8080
  application:
    name: graphql

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
    url:
      enabled: true

graphql:
  path: /
  # if enabled, this is a webapp client to send graphql requests
  graphiql:
    enabled: true
    path: /graphiql
    template-path: classpath:graphiql/index.html
    page-title: GraphiQL

rethinkdb:
  port: ${RETHINK_PORT:28015}
  host: ${RETHINK_HOST:localhost}
