name: crypto-analyzer project Python CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'crypto-analyzer/**'
      - '!crypto-analyzer/README.md'

jobs:
  build-python-modules:
    runs-on: ubuntu-latest
    name: Build python modules

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --upgrade pip pipenv flake8
          cd crypto-analyzer/
          pipenv install --system --deploy
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
