name: cryptobot CI

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-gradle-modules:
    runs-on: ubuntu-latest
    name: Build gradle modules

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Execute script to build all
        run: cd ci-scripts/ && bash build_gradle_modules.sh

  build-python-modules:
    runs-on: ubuntu-latest
    name: Build python modules
    strategy:
      matrix:
        python-version: [ 2.7, 3.5, 3.6, 3.7, 3.8 ]

      steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pipenv
            pip install flake8
            pipenv install --system --deploy
        - name: Lint with flake8
        - run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

