name: crypto-analyzer project publish image

on:
  push:
    branches: [ master ]
    paths:
      - 'crypto-analyzer/**'
      - '!crypto-analyzer/README.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish docker image to ghcr
        working-directory: ./ci-scripts
        run: bash build_image_and_publish.sh crypto-analyzer ${{ secrets.PAT_GHCR }}
