name: cryptobot CI

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-gradle-modules:
    runs-on: ubuntu-latest
    name: Build gradle modules

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Execute script to build all
        run: cd ci/ && bash build_gradle_modules.sh

  build-python-modules:
    runs-on: ubuntu-latest
    name: Build python modules

    steps:
      - uses: actions/checkout@v2
      - name: Build it
        run: echo "hello builing python!"

